# this only test the channel namespace promotion logic. TODO: need to find a way
# to test the object store got the promoted object
--- 
apiVersion: apps.open-cluster-management.io/v1
kind: Deployable
metadata: 
  name: payload-cfg-obj-channel
  annotations: 
    app.ibm.com/is-local-deployable: "false"
  namespace: default
spec: 
  channels: 
  - backend-test
  template: 
    apiVersion: v1
    data: 
      database: mongodb
    kind: ConfigMap
    metadata: 
      name: cfg-from-ch-qa
---
apiVersion: v1
kind: Namespace
metadata:
  name: ch-obj
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: backend-test
  namespace: ch-obj
spec:
  type: ObjectBucket
  pathname: http://minio-minio.apps.hivemind-b.aws.red-chesterfield.com/backend-test
  sourceNamespaces:
    - default
  secretRef:
    name: dev
---
apiVersion: v1
kind: Secret
metadata:
  name: dev
  namespace: ch-obj
data:
  AccessKeyID: 8WzMANMhF1DNwfBxl52q #<base64 encode username>
  SecretAccessKey: J8UQo0s5VY8cZmFw4u5DdC47ufB7XvMvDjT5Sg0q #<base64 encode password>
