---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: channel-validating-webhook-configuration
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
- clientConfig:
    caBundle: ${CA_BUNDLE}
    service:
      name: channel-webhook-service
      namespace: default
      path: /validate-apps-open-cluster-management-io-v1-channel
  failurePolicy: Fail
  name: vchannel.kb.io
  rules:
  - apiGroups:
    - apps.open-cluster-management.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - channels
