apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicloud-operators-channel
  labels:
    name: multicloud-operators-channel
spec:
  replicas: 1
  selector:
    matchLabels:
      name: multicloud-operators-channel
  template:
    metadata:
      labels:
        name: multicloud-operators-channel
    spec:
      serviceAccountName: multicloud-operators
      containers:
        - name: multicloud-operators-channel
          imagePullPolicy: Never
          image: quay.io/open-cluster-management/multicloud-operators-channel:3.5.0-PR28-104a3af217dbff21b6f537a1f6ebabf9766a4013
          ports:
          - containerPort: 8443
          command:
          - /usr/local/bin/multicloud-operators-channel
          - --sync-interval=10
          env:
            - name: WATCH_NAMESPACE
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "multicloud-operators-channel"
          resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
